In [23]:
def print_mat(mat, lines):
    for i in range(0, len(mat)):
        print(mat[i], lines[i])

In [27]:
import numpy as np
inputs = ['toes', 'win', 'fans']
hidden = ['hid1', 'hid2', 'hid3']
outputs = ['hurt', 'win', 'sad']

print('weights')
ih = np.random.rand(3, 3)
print('         ,'.join(inputs))
print_mat(ih, hidden)
print()
ho = np.random.rand(3, 3)
print('         ,'.join(inputs))
print_mat(ho, hidden)

weights
toes         ,win         ,fans
[0.12766139 0.42200263 0.95983489] hid1
[0.54994399 0.43667749 0.41370014] hid2
[0.20053212 0.67102396 0.4567119 ] hid3

toes         ,win         ,fans
[0.85891362 0.71087062 0.42075114] hid1
[0.18610717 0.01422632 0.07157054] hid2
[0.07597912 0.57312814 0.74463691] hid3


In [32]:
def next_layer_values(weights, inp):
    output = []
    for i in range(0, len(weights)):
        result = 0
        for j in range(0, len(inp)):
            result+=weights[i][j]*inp[j]
        output.append(result)
    return output

In [36]:
input_data = np.random.randint(100,size=3)
print(input_data)

[33 92 89]


In [38]:
hidden_input = next_layer_values(ih, input_data)
print(hidden_input)

[128.4623730390004, 95.1417927568425, 108.99912273375864]


In [39]:
output = next_layer_values(ho, hidden_input)
print(output)

[223.83309143914138, 33.06241245039443, 145.45366743976683]
