In [42]:
import numpy as np
r_weights = np.random.rand(3,3)
print(r_weights)

[[0.8581734  0.38396084 0.56711249]
 [0.98337011 0.83935486 0.00508765]
 [0.91151641 0.80291966 0.40883734]]


In [43]:
input_data = np.random.randint(500, size=3)
print(input_data)

[ 47 365 188]


In [44]:
output_data = np.random.randint(1000, size=3)
print(output_data)

[211 770 673]


In [52]:
weights = r_weights.copy()
def m_sum(weights, input):
    output=0
    for j in range(0, len(input)):
        output=weights[j] * input[j]
    return output

def predict(weights, inp):
    output = []
    for i in range(0, len(weights)):
        result = m_sum(weights[i], inp)
        output.append(result)
    return output
 
def learn(input, label):
    lr=0.01
    for i in range(0, len(weights)):
        l_weights = weights[i]
        output = m_sum(l_weights, input)
        loss = (label[i] - output)**2
        #positive test case
        p_weights = [i + lr for i in l_weights]
        p_output = m_sum(p_weights, input)
        p_loss = (label[i] - p_output)**2
        if p_loss < loss:
            weights[i] = p_weights
        
        
        #negative weights
        n_weights = [i - lr for i in l_weights]
        n_output = m_sum(n_weights, input)
        n_loss = (label[i] - n_output)**2
        if n_loss < loss:
            weights[i] = n_weights
            
print('initial_prediction', predict(weights, input_data))
print('expected_output', output_data)
for i in range(100000):
    learn(input_data, output_data)
print('final_prediction', predict(weights, input_data))

initial_prediction [106.61714897850271, 0.9564787602677645, 76.86142085309402]
expected_output [211 770 673]
final_prediction [211.8971489785028, 769.8764787602597, 672.821420853088]
